# Generated by Django 5.1.4 on 2025-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevBlog', '0003_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
